# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cfe1e8946a65e56cf8b7fca09e901bf8971b34b477fa1cd72c1a4018c9226bfacf093d7ec363db9fe1ed391bde4724db1060b3bd6ea6000e88b8bfa80f22cfe

test:
  secret_key_base: 1aca03cca0ced4bd7f989480fd332693592daaf88a0ef51d8503d367d971ea5486793bd5fc4776aa7ac4301f37940d1ec9e11b242d8cd7ec5453544ba2b63c8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
